### ISSUE TITLE
PHP Notices

### ISSUE THREAD

**Issue by dmhendricks** [monkeyscode/customizer#5]
It seems that this library is throwing notices if array values are not set. For example, if I don't want to set an `info:priority`, I get "Notice: Undefined index: priority." If I don't want to set `fields:default`, I get "Undefined index: default", etc...

It would be nice if the various methods would do an `isset()` to avoid these notices, since my default development environment is configured to display PHP notices (which breaks the UI).

Nice work!
Daniel

**Comment by duyngha** [comment]
@dmhendricks 
I updated to fix PHP notice and updated some validation for data input. If your problem has not resolved yet, please reopen this issue so I can check it deeply.

Thanks
Duy
